language: node_js
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
  slack:
    rooms:
      secure: lRmRj+cbE/OIcV4mIX1wg8BUhPgq68TIlUnQtNVGJIhzQnxdN/vNQVxEhO8CJe9Z9qH6xyf2g7a37DWYomM4+g7H1kJc3YP6j0AI/mmW3tbpK58qE3Lm9mobx+7M2GMcZg8s4F1mQXd6d1ZHvVO+F49lAOYFg4Td3RUoWSYTfgiLLQiRyBTYc3RbVIjd9EK0LKpElVAWbsdSs8V5djWQavxnb8Rs49eRjaaNPrSlxhmQFv+EsWQs+eFzi6LpHNqKVRJT8FQ0wQYbjn7Mkv67pJcyaFRbW7xGPwG+uXbXvL/yhqs6UiJMVa5R0WMCE8qOCC8fnqm353QlmKu8xIMp5MXj2w2vzpzbKzw8vDKe3Yz1jd8efiBTzs9AZi4QlIvElqWBmpWmRI0Rrr7kL54aIIctoHx2IJW2cWpdjJ2P9UApdBhqJZ+FTfv8rwoUVh7dEN2ACZ6BLzjg+sVeKvNw7O7E84GnX+5teZemgNpw1inM0oJ1Ho5W8Pu9bg2smB9hHjTvhjVk2Eebm27E4pMVvqUUKzI6VQf83R9M4NxC11JE8JN1R8fI5AR0OiGMisY5t+0pL9F8qGVnOW4T4pg+Ro3tLVnOmfnYzwgSGW9wW9ta+3vE6v/Xr36bDmIkZy2YlLCETaCKbJYBtGuU88Ejruez7BRNnNz2jdI+Qu20DAY=
node_js:
- node
script:
- npm run test:prod && npm run build
after_success:
- npm run report-coverage
- npm run deploy-docs
deploy:
  provider: npm
  skip_cleanup: true
  email: tim@arch-iot.com
  api_key:
    secure: Lu9Z3KCO7Goz7JHQZ79MNYiBQjvAzYAWpDBDiPGJrRflwh1QTOtd4hKu+cU1XSuI6rR2rBFbobzE/4jnCVoPdXPWHBFMJEjwtBWWI0QM3k/Uo3wPdSysCqMHGV8HWqrFeymibb71LMl+7GCkWcygDRqpR1+2SWHiBS6V6ii9syP2dq3lOJ/3VKFdUtimdbNMiIZoDeBCXqLfFDexLf0OR6OAK3rWd9SpiGNVgRoYmCxtaOSWgBAgPo8KsEqmuY/UwegiBSckTWKdRK22Ra4tdrG42vR7+RuKXi/xAC7AleTwHPkM2/sK+yI4JaMdiea3N5IoHOAMZQecMyCciaR7buusm7AReG0PopYPmxsLCf4RlkyEmdUO6pIJ7oRd0rcFL+vmYQEbvJDiYRJbjEAn76DeZBmjCyvYSZ1bsqEVju4ZqtoBekp38wTNArQ3cbm6m4RXeKHWIcNtnsrkF4/nmiZoo90+Cdbu24QJ7fSQ9+TmK9DF25KsNfC50nYipZ/ly96FfpapnIYm3V3eP+y7n5im/GnwQpYy2TXVFtx+cV/hWf4v6JacskYXbyz6G0H/2/B6crTvr5j7ZPz2MnWnX71YVvadCQU3JFrxSJzWQSodtfKF4AQRV4OiaH1T1jcfAho7CtiEFrsIjsfClK9P3GcBepMnpdrVFSRWpFlQw2M=
  on:
    tags: true
    branch: master
